Update openwrt startup scripts for olsrd2 and dlep_proxy

diff --git a/openwrt/oonf-olsrd2-git/files/olsrd2.init b/openwrt/oonf-olsrd2-git/files/olsrd2.init
--- a/openwrt/oonf-olsrd2-git/files/olsrd2.init
+++ b/openwrt/oonf-olsrd2-git/files/olsrd2.init
@@ -2,143 +2,145 @@
 
 START=82
 
+daemon=olsrd2
+
 . /usr/share/libubox/jshn.sh
 
-olsrd2_log()
+oonf_log()
 {
-	logger -s -t olsrd2 -p daemon.info "$1"
+  logger -s -t ${daemon} -p daemon.info "$1"
 }
 
-olsrd2_get_layer3_device()
+oonf_get_layer3_device()
 {
-	local interface="$1"	# e.g. 'mywifi'
-	local status dev proto
-	local query="{ \"interface\" : \"$interface\" }"
+  local interface="$1"  # e.g. 'mywifi'
+  local status dev proto
+  local query="{ \"interface\" : \"$interface\" }"
 
-	status="$( ubus -S call network.interface status "$query" )" && {
-		json_load "$status"
-		json_get_var 'dev' l3_device
-		json_get_var 'proto' proto
+  status="$( ubus -S call network.interface status "$query" )" && {
+    json_load "$status"
+    json_get_var 'dev' l3_device
+    json_get_var 'proto' proto
 
-		case "$proto" in
-			pppoe)
-				# TODO: otherwise it segfaults
-				olsrd2_log "refusing to add '$interface', because of proto '$proto'"
-			;;
-			*)
-				echo "$dev"	# e.g. 'wlan0-1'
-			;;
-		esac
-	}
+    case "$proto" in
+      pppoe)
+        # TODO: otherwise it segfaults
+        oonf__log "refusing to add '$interface', because of proto '$proto'"
+      ;;
+      *)
+        echo "$dev" # e.g. 'wlan0-1'
+      ;;
+    esac
+  }
 }
 
-olsrd2_add_devices_to_configuration()
+oonf_add_devices_to_configuration()
 {
-	local i=0
-	local j=0
-	local device_name= dummy= interface= single_interface=
+  local i=0
+  local j=0
+  local device_name= dummy= interface= single_interface=
 
-	# make a copy of configuration and
-	# replace all 'interface-names' (e.g. mywifi)
-	# with the real devices (e.g. wlan0-1)
-	#
-	# look over original interfaces, e.g.
-	#
-	# olsrd2.@interface[2]=interface
-	# olsrd2.@interface[2].ifname='wan lan wlanadhoc wlanadhocRADIO1'
+  # make a copy of configuration and
+  # replace all 'interface-names' (e.g. mywifi)
+  # with the real devices (e.g. wlan0-1)
+  #
+  # look over original interfaces, e.g.
+  #
+  # olsrd2.@interface[2]=interface
+  # olsrd2.@interface[2].ifname='wan lan wlanadhoc wlanadhocRADIO1'
 
-	# /var is in ramdisc/tmpfs
-	cp /etc/config/olsrd2 /var/etc/olsrd2_dev
+  # /var is in ramdisc/tmpfs
+  cp /etc/config/${daemon} /var/etc${daemon}_dev
 
-	while dummy="$( uci -q -c /etc/config get "olsrd2.@interface[$i]" )"; do {
-		interface="$( uci -q -c /etc/config get "olsrd2.@interface[$i].ifname" )" || {
-			i=$(( $i + 1 ))
-			j=$(( $j + 1 ))
+  while dummy="$( uci -q -c /etc/config get "${daemon}.@interface[$i]" )"; do {
+    interface="$( uci -q -c /etc/config get "${daemon}.@interface[$i].ifname" )" || {
+      i=$(( $i + 1 ))
+      j=$(( $j + 1 ))
 
-			continue
-		}
+      continue
+    }
 
-		case "$( uci -q get "olsrd2.@interface[$i].ignore" )" in
-			1|on|true|enabled|yes)
-				olsrd2_log "removing/ignore interface '$interface'"
-				uci -q -c /var/etc delete "olsrd2_dev.@interface[$j]"
-				i=$(( $i + 1 ))
+    case "$( uci -q get "${daemon}.@interface[$i].ignore" )" in
+      1|on|true|enabled|yes)
+        oonf_log "removing/ignore interface '$interface'"
+        uci -q -c /var/etc delete "${daemon}_dev.@interface[$j]"
+        i=$(( $i + 1 ))
 
-				continue
-			;;
-		esac
+        continue
+      ;;
+    esac
 
-		for single_interface in $interface; do {
-			device_name="$( olsrd2_get_layer3_device "$single_interface" )"
+    for single_interface in $interface; do {
+      device_name="$( oonf_get_layer3_device "$single_interface" )"
 
-			[ -z "$device_name" ] && {
-				# remove from copy
-				uci -q -c /var/etc delete "olsrd2_dev.@interface[$j]"
-				i=$(( $i + 1 ))
+      [ -z "$device_name" ] && {
+        # remove from copy
+        uci -q -c /var/etc delete "${daemon}_dev.@interface[$j]"
+        i=$(( $i + 1 ))
 
-				continue
-			}
+        continue
+      }
 
-			# replace option 'ifname' (e.g. 'mywifi')
-			# with the option 'name' (e.g. 'wlan0-1')
+      # replace option 'ifname' (e.g. 'mywifi')
+      # with the option 'name' (e.g. 'wlan0-1')
 
-			# var 'ifname' is not needed anymore, but we keep it for readability
-			uci -q -c /var/etc set    "olsrd2_dev.@interface[$j].ifname=$single_interface"
+      # var 'ifname' is not needed anymore, but we keep it for readability
+      uci -q -c /var/etc set    "${daemon}_dev.@interface[$j].ifname=$single_interface"
 
-			uci -q -c /var/etc set    "olsrd2_dev.@interface[$j].name=$device_name" || {
-				# fails if index '$j' is wrong (multiple interface for 1 section)
-				uci -q -c /var/etc add olsrd2_dev 'interface' >/dev/null
-				uci -q -c /var/etc set olsrd2_dev.@interface[-1].ifname="$single_interface"
-				uci -q -c /var/etc set olsrd2_dev.@interface[-1].name="$device_name"
-			}
+      uci -q -c /var/etc set    "${daemon}_dev.@interface[$j].name=$device_name" || {
+        # fails if index '$j' is wrong (multiple interface for 1 section)
+        uci -q -c /var/etc add ${daemon}_dev 'interface' >/dev/null
+        uci -q -c /var/etc set ${daemon}_dev.@interface[-1].ifname="$single_interface"
+        uci -q -c /var/etc set ${daemon}_dev.@interface[-1].name="$device_name"
+      }
 
-			i=$(( $i + 1 ))
-			j=$(( $j + 1 ))
-		} done
-	} done
+      i=$(( $i + 1 ))
+      j=$(( $j + 1 ))
+    } done
+  } done
 
-	uci -q -c /var/etc commit olsrd2_dev
+  uci -q -c /var/etc commit ${daemon}_dev
 
-	# hide our old vars 'ifname' - it confuses the daemon parser
-	sed -i 's/option ifname /# &/' /var/etc/olsrd2_dev
+  # hide our old vars 'ifname' - it confuses the daemon parser
+  sed -i 's/option ifname /# &/' /var/etc/${daemon}_dev
 
-	olsrd2_log "wrote '/var/etc/olsrd2_dev'"
+  oonf_log "wrote '/var/etc/${daemon}_dev'"
 }
 
-olsrd2_reread_config()
+oonf_reread_config()
 {
-	local pid
-	local pidfile='/var/run/olsrd2.pid'
+  local pid
+  local pidfile='/var/run/${daemon}.pid'
 
-	if   [ -e "$pidfile" ]; then
-		read pid <"$pidfile"
-	elif pidfile="$( uci -q get 'olsrd2.@global[0].pidfile' )"; then
-		read pid <"$pidfile"
-	fi
+  if   [ -e "$pidfile" ]; then
+    read pid <"$pidfile"
+  elif pidfile="$( uci -q get '${daemon}.@global[0].pidfile' )"; then
+    read pid <"$pidfile"
+  fi
 
-	# if empty, ask kernel
-	pid="${pid:-$( pidof olsrd2 )}"
+  # if empty, ask kernel
+  pid="${pid:-$( pidof ${daemon} )}"
 
-	[ -n "$pid" ] && kill -SIGHUP $pid
+  [ -n "$pid" ] && kill -SIGHUP $pid
 }
 
 start()
 {
-	olsrd2_add_devices_to_configuration
+  oonf_add_devices_to_configuration
 
-	# produce coredumps
-	ulimit -c unlimited
+  # produce coredumps
+  ulimit -c unlimited
 
-	service_start /usr/sbin/olsrd2 --set global.fork=true --load uci:///var/etc/olsrd2_dev
+  service_start /usr/sbin/${daemon} --set global.fork=true --load uci:///var/etc/${daemon}_dev
 }
 
 stop()
 {
-	service_stop /usr/sbin/olsrd2
+  service_stop /usr/sbin/${daemon}
 }
 
 reload()
 {
-	olsrd2_add_devices_to_configuration
-	olsrd2_reread_config
+  oonf_add_devices_to_configuration
+  oonf_reread_config
 }
